classDiagram
  class AbstractSelectionPage {
  }
  class Acquisition {
  }
  class AcquisitionList {
  }
  class AcquisitionListBuilder {
  }
  class AcquisitionModel {
  }
  class CheckTilingPage {
  }
  class ChooseFolderDelegate {
  }
  class ComboDelegate {
  }
  class DCAMAPI_INIT {
  }
  class DCAMBUF_ATTACH {
  }
  class DCAMBUF_FRAME {
  }
  class DCAMCAP_TRANSFERINFO {
  }
  class DCAMDEV_OPEN {
  }
  class DCAMDEV_STRING {
  }
  class DCAMPROP_ATTR {
  }
  class DCAMPROP_VALUETEXT {
  }
  class DCAMWAIT_OPEN {
  }
  class DCAMWAIT_START {
  }
  class DefineBoundingBoxPage {
  }
  class DefineFolderPage {
  }
  class DefineGeneralParametersPage {
  }
  class DemoZoom {
  }
  class Demo_Camera {
  }
  class Demo_JoystickHandler {
  }
  class Demo_LaserEnabler {
  }
  class Demo_Shutter {
  }
  class Demo_SidePanel {
  }
  class DynamixelFilterWheel {
  }
  class DynamixelZoom {
  }
  class EFW {
  }
  class EFW_Error {
  }
  class EFW_IOError {
  }
  class ETLSpinBoxDelegate {
  }
  class FarmSimulatorSidePanel {
  }
  class FifthChannelPage {
  }
  class FilenameWizard {
  }
  class FilenameWizardBigTiffSelectionPage {
  }
  class FilenameWizardCheckResultsPage {
  }
  class FilenameWizardRawSelectionPage {
  }
  class FilenameWizardSingleHDF5SelectionPage {
  }
  FilenameWizardSingleOmeZarrSelectionPage {
  }
  class FilenameWizardTiffSelectionPage {
  }
  class FilenameWizardWelcomePage {
  }
  class FinishedTilingPage {
  }
  class FirstChannelPage {
  }
  class FocusTrackingWizard {
  }
  class FocusTrackingWizardCheckResultsPage {
  }
  class FocusTrackingWizardSetReferencePointsPage {
  }
  class FocusTrackingWizardWelcomePage {
  }
  class FourthChannelPage {
  }
  class GclibError {
  }
  class GenericChannelPage {
  }
  class HCamData {
  }
  class HamamatsuCamera {
  }
  class HamamatsuCameraMR {
  }
  class ImageProcessingWizard {
  }
  class ImageProcessingWizardCheckResultsPage {
  }
  class ImageProcessingWizardSetOptionsPage {
  }
  class ImageProcessingWizardWelcomePage {
  }
  class IntensitySpinBoxDelegate {
  }
  class LudlFilterWheel {
  }
  class MarkFocusPositionDelegate {
  }
  class MarkPositionDelegate {
  }
  class MarkPositionWidget {
  }
  class MarkRotationPositionDelegate {
  }
  class MarkXPositionDelegate {
  }
  class MarkYPositionDelegate {
  }
  class MarkZPositionDelegate {
  }
  class MitutoyoZoom {
  }
  class MulticolorTilingAcquisitionListBuilder {
  }
  class MulticolorTilingWizard {
  }
  class MyStyle {
  }
  class NI_Shutter {
  }
  class ProgressBarDelegate {
  }
  class PythonHighlighter {
  }
  class RotationSpinBoxDelegate {
  }
  class SecondChannelPage {
  }
  class SliderDelegate {
  }
  class SliderWithValue {
  }
  class SliderWithValueDelegate {
  }
  class StageControlASITiger {
  }
  class StageControlGalil {
  }
  class SutterLambda10BFilterWheel {
  }
  class TestFilterWheel {
  }
  class TestTilingWizard {
  }
  class TestZoomServo {
  }
  class ThirdChannelPage {
  }
  class TilingWelcomePage {
  }
  class VirtualStages {
  }
  class WebcamWindow {
  }
  class ZstepSpinBoxDelegate {
  }
  class ZwoFilterWheel {
  }
  class _EFW_INFO {
  }
  class mesoSPIM_ASI_MS2000_Stage {
  }
  class mesoSPIM_ASI_Tiger_Stage {
  }
  class mesoSPIM_AcquisitionManagerWindow {
  }
  class mesoSPIM_Camera {
  }
  class mesoSPIM_CameraWindow {
  }
  class mesoSPIM_ContrastWindow {
  }
  class mesoSPIM_Core {
  }
  class mesoSPIM_DemoCamera {
  }
  class mesoSPIM_DemoFilterWheel {
  }
  class mesoSPIM_DemoStage {
  }
  class mesoSPIM_DemoWaveFormGenerator {
  }
  class mesoSPIM_GenericCamera {
  }
  class mesoSPIM_HamamatsuCamera {
  }
  class mesoSPIM_ImageWriter {
  }
  class mesoSPIM_JoystickHandler {
  }
  class mesoSPIM_LaserEnabler {
  }
  class mesoSPIM_MainWindow {
  }
  class mesoSPIM_Optimizer {
  }
  class mesoSPIM_PCOCamera {
  }
  class mesoSPIM_PI_1toN {
  }
  class mesoSPIM_PI_NtoN {
  }
  class mesoSPIM_PI_rotz_and_Galil_xyf_Stages {
  }
  class mesoSPIM_PhotometricsCamera {
  }
  class mesoSPIM_ScriptWindow {
  }
  class mesoSPIM_Serial {
  }
  class mesoSPIM_Stage {
  }
  class mesoSPIM_StateSingleton {
  }
  class mesoSPIM_TileViewWindow {
  }
  class mesoSPIM_WaveFormGenerator {
  }
  class py {
  }
  HamamatsuCameraMR --|> HamamatsuCamera
  EFW_IOError --|> EFW_Error
  mesoSPIM_DemoCamera --|> mesoSPIM_GenericCamera
  mesoSPIM_HamamatsuCamera --|> mesoSPIM_GenericCamera
  mesoSPIM_PCOCamera --|> mesoSPIM_GenericCamera
  mesoSPIM_PhotometricsCamera --|> mesoSPIM_GenericCamera
  mesoSPIM_ASI_MS2000_Stage --|> mesoSPIM_Stage
  mesoSPIM_ASI_Tiger_Stage --|> mesoSPIM_Stage
  mesoSPIM_DemoStage --|> mesoSPIM_Stage
  mesoSPIM_PI_1toN --|> mesoSPIM_Stage
  mesoSPIM_PI_NtoN --|> mesoSPIM_Stage
  mesoSPIM_PI_rotz_and_Galil_xyf_Stages --|> mesoSPIM_Stage
  mesoSPIM_DemoWaveFormGenerator --|> mesoSPIM_WaveFormGenerator
  MarkFocusPositionDelegate --|> MarkPositionDelegate
  MarkRotationPositionDelegate --|> MarkPositionDelegate
  MarkXPositionDelegate --|> MarkPositionDelegate
  MarkYPositionDelegate --|> MarkPositionDelegate
  MarkZPositionDelegate --|> MarkPositionDelegate
  FilenameWizardBigTiffSelectionPage --|> AbstractSelectionPage
  FilenameWizardSingleHDF5SelectionPage --|> AbstractSelectionPage
  FilenameWizardTiffSelectionPage --|> AbstractSelectionPage
  FilenameWizardSingleOmeZarrSelectionPage  --|> AbstractSelectionPage
  FifthChannelPage --|> GenericChannelPage
  FirstChannelPage --|> GenericChannelPage
  FourthChannelPage --|> GenericChannelPage
  SecondChannelPage --|> GenericChannelPage
  ThirdChannelPage --|> GenericChannelPage
  WebcamWindow --* mesoSPIM_MainWindow : webcam_window
  WebcamWindow --* mesoSPIM_MainWindow : webcam_window
  HamamatsuCameraMR --* mesoSPIM_HamamatsuCamera : hcam
  EFW --* ZwoFilterWheel : device
  DynamixelFilterWheel --* mesoSPIM_Serial : filterwheel
  LudlFilterWheel --* mesoSPIM_Serial : filterwheel
  SutterLambda10BFilterWheel --* mesoSPIM_Serial : filterwheel
  ZwoFilterWheel --* mesoSPIM_Serial : filterwheel
  mesoSPIM_DemoFilterWheel --* mesoSPIM_Serial : filterwheel
  Demo_SidePanel --* mesoSPIM_JoystickHandler : joystick
  FarmSimulatorSidePanel --* mesoSPIM_JoystickHandler : joystick
  mesoSPIM_JoystickHandler --* mesoSPIM_MainWindow : joystick
  Demo_LaserEnabler --* mesoSPIM_Core : laserenabler
  mesoSPIM_LaserEnabler --* mesoSPIM_Core : laserenabler
  Demo_Shutter --* mesoSPIM_Core : shutter_left
  Demo_Shutter --* mesoSPIM_Core : shutter_right
  NI_Shutter --* mesoSPIM_Core : shutter_left
  NI_Shutter --* mesoSPIM_Core : shutter_right
  StageControlASITiger --* mesoSPIM_ASI_Tiger_Stage : asi_stages
  StageControlGalil --* mesoSPIM_PI_rotz_and_Galil_xyf_Stages : xyf_stage
  py --* StageControlGalil : g
  mesoSPIM_AcquisitionManagerWindow --* mesoSPIM_MainWindow : acquisition_manager_window
  mesoSPIM_Camera --* mesoSPIM_Core : camera_worker
  mesoSPIM_DemoCamera --* mesoSPIM_Camera : camera
  mesoSPIM_HamamatsuCamera --* mesoSPIM_Camera : camera
  mesoSPIM_PCOCamera --* mesoSPIM_Camera : camera
  mesoSPIM_PhotometricsCamera --* mesoSPIM_Camera : camera
  mesoSPIM_CameraWindow --* mesoSPIM_MainWindow : camera_window
  mesoSPIM_ContrastWindow --* mesoSPIM_MainWindow : contrast_window
  mesoSPIM_Core --* mesoSPIM_MainWindow : core
  mesoSPIM_ImageWriter --* mesoSPIM_Core : image_writer
  mesoSPIM_Optimizer --* mesoSPIM_MainWindow : optimizer
  PythonHighlighter --* mesoSPIM_ScriptWindow : highlight
  mesoSPIM_ScriptWindow --* mesoSPIM_MainWindow : scriptwindow
  mesoSPIM_Serial --* mesoSPIM_Core : serial_worker
  mesoSPIM_ASI_MS2000_Stage --* mesoSPIM_Serial : stage
  mesoSPIM_ASI_Tiger_Stage --* mesoSPIM_Serial : stage
  mesoSPIM_DemoStage --* mesoSPIM_Serial : stage
  mesoSPIM_PI_1toN --* mesoSPIM_Serial : stage
  mesoSPIM_PI_NtoN --* mesoSPIM_Serial : stage
  VirtualStages --* mesoSPIM_PI_NtoN : pi_stages
  mesoSPIM_PI_rotz_and_Galil_xyf_Stages --* mesoSPIM_Serial : stage
  mesoSPIM_StateSingleton --* mesoSPIM_MainWindow : state
  mesoSPIM_TileViewWindow --* mesoSPIM_MainWindow : tile_view_window
  mesoSPIM_DemoWaveFormGenerator --* mesoSPIM_Core : waveformer
  mesoSPIM_WaveFormGenerator --* mesoSPIM_Core : waveformer
  DemoZoom --* mesoSPIM_Serial : zoom
  DynamixelZoom --* mesoSPIM_Serial : zoom
  MitutoyoZoom --* mesoSPIM_Serial : zoom
  AcquisitionList --* MulticolorTilingWizard : acq_list
  AcquisitionModel --* mesoSPIM_AcquisitionManagerWindow : model
